DROP TABLE Book CASCADE CONSTRAINTS;
DROP TABLE Librarian CASCADE CONSTRAINTS;
DROP TABLE LibraryCard CASCADE CONSTRAINTS;
DROP TABLE ReadingGroup CASCADE CONSTRAINTS;
DROP TABLE Transaction CASCADE CONSTRAINTS;
DROP TABLE BookCopy CASCADE CONSTRAINTS;
DROP TABLE Authors CASCADE CONSTRAINTS;
DROP TABLE Joins CASCADE CONSTRAINTS;
